console.log(" ")
console.log("**************************YOUR RESULT**************************")
console.log(" ")
console.log("COLLEGE: Ambalika institute , Lucknow")
console.log("NAME: Mayank Guta")
console.log("ROLL NUMBER: 2003630100104")
console.log("SUBJECTS:      Marks1      Marks2     TOTAL")
console.log("CH-102          15          40         55")
console.log("CS-102          12          36         48")
console.log("MA-111          16          48         64")
console.log("CS-107          20          49         69")
console.log("EE-101          12          39         50")
console.log("ΜΕ-101          19          50         88")
console.log(" ")
console.log("TOTAL MARKS: 356                RESULT: PASS")